apiVersion: v1
kind: Pod
metadata:
  name: vprodb
  labels:
    env: test
spec:
  containers:
    - name: vprodb
      image: vproject360/vprojectdb:V1
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "key1"
      operator: "Exists"
      effect: "NoSchedule"
